steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'gcr.io/$PROJECT_ID/deploy-test', 
    '.'
    ]
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/deploy-test']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta',
    'run',
    'deploy',
    '--allow-unauthenticated',
    'deploy-test',
    '--image',
    'gcr.io/$PROJECT_ID/deploy-test',
    '--region',
    'us-central1',
    '--platform',
    'managed',
    '--memory',
    '256Mi',
    '--update-env-vars',
    'APP_DEBUG=${_APP_DEBUG}'
    ]
images:
- gcr.io/$PROJECT_ID/deploy-test

options:
    substitution_option: 'ALLOW_LOOSE'

substitutions:
    _APP_DEBUG: 'true'
